language: python
python:
  - 2.6
  - 2.7
before_script:
  - "cp stashdaddy/local_settings.py.sample stashdaddy/local_settings.py"
  - psql -c 'create database stashdaddy;' -U postgres
intsall: pip install -r requirements.txt
script: python manage.py test accounts
